name: flutter_adaptive_buttons
description: A collection of Flutter widgets that adapt their appearance based on the platform and provide consistent button functionalities across different platforms.
version: 0.0.1
homepage: https://github.com/nikiforosper/flutter_adaptive_buttons

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
